services:
  - type: web
    name: nodule-detector
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 5000
      - key: PYTHON_WORKER_TIMEOUT
        value: 120
